export const dummyAnnouncementData = {
  content: [
    {
      complaintId: 10,
      complaintCategoryRespDTO: {
        complaintCategory: 2,
        name: '공동생활',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 3,
        nickname: '삼용자',
      },
      title: '분리수거 관련',
      createdAt: '2024-05-24 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 12,
      complaintCategoryRespDTO: {
        complaintCategory: 2,
        name: '공동생활',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 3,
        nickname: '삼용자',
      },
      title: '축구경기 뷰잉 파티',
      createdAt: '2024-05-24 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 9,
      complaintCategoryRespDTO: {
        complaintCategory: 2,
        name: '공동생활',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 2,
        nickname: '이용자',
      },
      title: '새벽 소음 관련 두번째',
      createdAt: '2024-05-23 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 11,
      complaintCategoryRespDTO: {
        complaintCategory: 2,
        name: '공동생활',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 2,
        nickname: '이용자',
      },
      title: '인도에서 타는 자전거',
      createdAt: '2024-05-23 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 8,
      complaintCategoryRespDTO: {
        complaintCategory: 13,
        name: '기타',
        type: 'RESIDENTS_COMMITTEE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 1,
        nickname: '일용자',
      },
      title: '업체 선발 관련 민원',
      createdAt: '2024-05-22 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 7,
      complaintCategoryRespDTO: {
        complaintCategory: 12,
        name: '건의사항',
        type: 'RESIDENTS_COMMITTEE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 1,
        nickname: '일용자',
      },
      title: '입대의 회의 내용 공유',
      createdAt: '2024-05-21 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 6,
      complaintCategoryRespDTO: {
        complaintCategory: 4,
        name: '주차장',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'SUBMITTED',
      writer: {
        memberId: 1,
        nickname: '일용자',
      },
      title: '다른동 주차구역에 주차',
      createdAt: '2024-05-21 01:58',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 3,
      complaintCategoryRespDTO: {
        complaintCategory: 3,
        name: '공동현관/복도',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'PROCESSING',
      writer: {
        memberId: 1,
        nickname: '일용자',
      },
      title: '4동 공동현관이 너무 더러워요',
      createdAt: '2024-05-16 22:47',
      view: 2,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 4,
      complaintCategoryRespDTO: {
        complaintCategory: 2,
        name: '공동생활',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'INVESTIGATING',
      writer: {
        memberId: 2,
        nickname: '이용자',
      },
      title: '새벽 소음 관련',
      createdAt: '2024-05-16 22:47',
      view: 7,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
    {
      complaintId: 5,
      complaintCategoryRespDTO: {
        complaintCategory: 7,
        name: '조명',
        type: 'MANAGEMENT_OFFICE',
      },
      complaintStatus: 'PROCESSING',
      writer: {
        memberId: 3,
        nickname: '삼용자',
      },
      title: '2동 앞 주차장에 불이 꺼졌어요',
      createdAt: '2024-05-16 22:47',
      view: 0,
      commentCnt: 0,
      agreeCnt: 0,
      secret: false,
    },
  ],
  totalPages: 10,
  totalElements: 100,
  pageNumber: 7,
  size: 10,
}
