name: Deploy

on:
  push:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v3

      - name: Install mustache (to update the date)
        run: apk add ruby && gem install mustache

      - name: Give execute permission to build.sh
        run: chmod +x ./build.sh

      - name: creates output
        run: ./build.sh

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.AUTO_ACTIONS }}
        with:
          source-directory: 'output'
          destination-github-username: subinsad
          destination-repository-name: FE_Project
          user-email: ${{ secrets.EMAIL }}
          commit-message: ${{ github.event.commits[0].message }}
          target-branch: main

      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY

